version: 2

build:
    os: "ubuntu-22.04"
    tools:
        python: "mambaforge-23.11"

conda:
    environment: environment.yml

sphinx:
    configuration: docs/source/conf.py
    fail_on_warning: false

python:
    install:
        - method: pip
          path: .
