# Reference:
#   - https://github.com/actions/checkout

---
name: ci-manifest

on:
  pull_request:
    branches:
      - "*"

  push:
    branches-ignore:
      - "dependabot/*"

  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  manifest:
    name: "check-manifest"

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "check-manifest"
        run: |
          pipx run check-manifest
